workspaces

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -589,71 +589,82 @@ jobs:
     environment:
       BUILD_ENVIRONMENT: << parameters.build-environment >>
     steps:
-      - checkout
-      - run_brew_for_macos_build
-
+      # - checkout
+      # - run_brew_for_macos_build
       - run:
-          name: Install sccache (only for non-forked PRs, and pushes to trunk)
+          name: test
           command: |
-            sudo curl --retry 3 https://s3.amazonaws.com/ossci-macos/sccache_v2.15 --output /usr/local/bin/sccache
-            sudo chmod +x /usr/local/bin/sccache
-            echo "export SCCACHE_BUCKET=ossci-compiler-cache-circleci-v2" >> "${BASH_ENV}"
-            echo "export SCCACHE_S3_KEY_PREFIX=${GITHUB_WORKFLOW}" >> "${BASH_ENV}"
-
-            set +x
-            echo "export AWS_ACCESS_KEY_ID=${CIRCLECI_AWS_ACCESS_KEY_FOR_SCCACHE_S3_BUCKET_V4}" >> "${BASH_ENV}"
-            echo "export AWS_SECRET_ACCESS_KEY=${CIRCLECI_AWS_SECRET_KEY_FOR_SCCACHE_S3_BUCKET_V4}" >> "${BASH_ENV}"
-            set -x
-
-      - run:
-          name: Get workflow job id
-          command: |
-            echo "export OUR_GITHUB_JOB_ID=${CIRCLE_WORKFLOW_JOB_ID}" >> "${BASH_ENV}"
-
-      - run:
-          name: Build
-          command: |
-            set -x
-
-            git submodule sync --recursive
-            git submodule update --init --recursive
-
-            export PATH="/usr/local/bin:$PATH"
+            set -ex
+            ls
+            pwd
             export WORKSPACE_DIR="${HOME}/workspace"
             mkdir -p "${WORKSPACE_DIR}"
+            cd ~/workspace
+            echo "a;dslfkja" >> "/Users/distiller/workspace/${BUILD_ENVIRONMENT}.txt"
 
-            MINICONDA_URL="https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-MacOSX-x86_64.sh"
+      # - run:
+      #     name: Install sccache (only for non-forked PRs, and pushes to trunk)
+      #     command: |
+      #       sudo curl --retry 3 https://s3.amazonaws.com/ossci-macos/sccache_v2.15 --output /usr/local/bin/sccache
+      #       sudo chmod +x /usr/local/bin/sccache
+      #       echo "export SCCACHE_BUCKET=ossci-compiler-cache-circleci-v2" >> "${BASH_ENV}"
+      #       echo "export SCCACHE_S3_KEY_PREFIX=${GITHUB_WORKFLOW}" >> "${BASH_ENV}"
 
-            # If a local installation of conda doesn't exist, we download and install conda
-            if [ ! -d "${WORKSPACE_DIR}/miniconda3" ]; then
-              mkdir -p "${WORKSPACE_DIR}"
-              curl --retry 3 ${MINICONDA_URL} -o "${WORKSPACE_DIR}"/miniconda3.sh
-              bash "${WORKSPACE_DIR}"/miniconda3.sh -b -p "${WORKSPACE_DIR}"/miniconda3
-            fi
-            export PATH="${WORKSPACE_DIR}/miniconda3/bin:$PATH"
-            # shellcheck disable=SC1091
-            source "${WORKSPACE_DIR}"/miniconda3/bin/activate
+      #       set +x
+      #       echo "export AWS_ACCESS_KEY_ID=${CIRCLECI_AWS_ACCESS_KEY_FOR_SCCACHE_S3_BUCKET_V4}" >> "${BASH_ENV}"
+      #       echo "export AWS_SECRET_ACCESS_KEY=${CIRCLECI_AWS_SECRET_KEY_FOR_SCCACHE_S3_BUCKET_V4}" >> "${BASH_ENV}"
+      #       set -x
 
-            echo "export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname "$(which conda)")/../"}" >> "${BASH_ENV}"
-            .jenkins/pytorch/macos-build.sh
+      # - run:
+      #     name: Get workflow job id
+      #     command: |
+      #       echo "export OUR_GITHUB_JOB_ID=${CIRCLE_WORKFLOW_JOB_ID}" >> "${BASH_ENV}"
 
-      - when:
-          condition: << parameters.build-generates-artifacts >>
-          steps:
-            - run:
-                name: Archive artifacts into zip
-                command: |
-                  zip -1 -r artifacts.zip dist/ build/.ninja_log build/compile_commands.json .pytorch-test-times.json
-                  cp artifacts.zip /Users/distiller/workspace
+      # - run:
+      #     name: Build
+      #     command: |
+      #       set -x
+
+      #       git submodule sync --recursive
+      #       git submodule update --init --recursive
+
+      #       export PATH="/usr/local/bin:$PATH"
+      #       export WORKSPACE_DIR="${HOME}/workspace"
+      #       mkdir -p "${WORKSPACE_DIR}"
+
+      #       MINICONDA_URL="https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-MacOSX-x86_64.sh"
+
+      #       # If a local installation of conda doesn't exist, we download and install conda
+      #       if [ ! -d "${WORKSPACE_DIR}/miniconda3" ]; then
+      #         mkdir -p "${WORKSPACE_DIR}"
+      #         curl --retry 3 ${MINICONDA_URL} -o "${WORKSPACE_DIR}"/miniconda3.sh
+      #         bash "${WORKSPACE_DIR}"/miniconda3.sh -b -p "${WORKSPACE_DIR}"/miniconda3
+      #       fi
+      #       export PATH="${WORKSPACE_DIR}/miniconda3/bin:$PATH"
+      #       # shellcheck disable=SC1091
+      #       source "${WORKSPACE_DIR}"/miniconda3/bin/activate
+
+      #       echo "export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname "$(which conda)")/../"}" >> "${BASH_ENV}"
+      #       .jenkins/pytorch/macos-build.sh
+
+      # - when:
+      #     condition: << parameters.build-generates-artifacts >>
+      #     steps:
+      #       - run:
+      #           name: Archive artifacts into zip
+      #           command: |
+      #             zip -1 -r artifacts.zip dist/ build/.ninja_log build/compile_commands.json .pytorch-test-times.json
+      #             cp artifacts.zip /Users/distiller/workspace
 
       - persist_to_workspace:
           root: /Users/distiller/workspace/
           paths:
-            - miniconda3
-            - artifacts.zip
+            # - miniconda3
+            # - artifacts.zip
+            - << parameters.build-environment >>.txt
 
-      - store_artifacts:
-          path: /Users/distiller/project/artifacts.zip
+      # - store_artifacts:
+      #     path: /Users/distiller/project/artifacts.zip
 
   mac_test:
     parameters:
@@ -680,69 +691,75 @@ jobs:
       - checkout
       - attach_workspace:
           at: ~/workspace
-      - run_brew_for_macos_build
       - run:
-          name: Test
-          no_output_timeout: "1h"
+          name: workspace
           command: |
             set -x
+            cd ~/workspace
+            ls
+      # - run_brew_for_macos_build
+      # - run:
+      #     name: Test
+      #     no_output_timeout: "1h"
+      #     command: |
+      #       set -x
 
-            git submodule sync --recursive
-            git submodule update --init --recursive
+      #       git submodule sync --recursive
+      #       git submodule update --init --recursive
 
-            mv ~/workspace/artifacts.zip .
-            unzip artifacts.zip
+      #       mv ~/workspace/artifacts.zip .
+      #       unzip artifacts.zip
 
-            export IN_CI=1
+      #       export IN_CI=1
 
-            COMMIT_MESSAGES=$(git cherry -v "origin/${GIT_DEFAULT_BRANCH:-master}")
+      #       COMMIT_MESSAGES=$(git cherry -v "origin/${GIT_DEFAULT_BRANCH:-master}")
 
-            export PATH="/usr/local/bin:$PATH"
-            export WORKSPACE_DIR="${HOME}/workspace"
-            mkdir -p "${WORKSPACE_DIR}"
+      #       export PATH="/usr/local/bin:$PATH"
+      #       export WORKSPACE_DIR="${HOME}/workspace"
+      #       mkdir -p "${WORKSPACE_DIR}"
 
-            MINICONDA_URL="https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-MacOSX-x86_64.sh"
+      #       MINICONDA_URL="https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-MacOSX-x86_64.sh"
 
-            # If a local installation of conda doesn't exist, we download and install conda
-            if [ ! -d "${WORKSPACE_DIR}/miniconda3" ]; then
-              mkdir -p "${WORKSPACE_DIR}"
-              curl --retry 3 ${MINICONDA_URL} -o "${WORKSPACE_DIR}"/miniconda3.sh
-              bash "${WORKSPACE_DIR}"/miniconda3.sh -b -p "${WORKSPACE_DIR}"/miniconda3
-            fi
-            export PATH="${WORKSPACE_DIR}/miniconda3/bin:$PATH"
-            # shellcheck disable=SC1091
-            source "${WORKSPACE_DIR}"/miniconda3/bin/activate
+      #       # If a local installation of conda doesn't exist, we download and install conda
+      #       if [ ! -d "${WORKSPACE_DIR}/miniconda3" ]; then
+      #         mkdir -p "${WORKSPACE_DIR}"
+      #         curl --retry 3 ${MINICONDA_URL} -o "${WORKSPACE_DIR}"/miniconda3.sh
+      #         bash "${WORKSPACE_DIR}"/miniconda3.sh -b -p "${WORKSPACE_DIR}"/miniconda3
+      #       fi
+      #       export PATH="${WORKSPACE_DIR}/miniconda3/bin:$PATH"
+      #       # shellcheck disable=SC1091
+      #       source "${WORKSPACE_DIR}"/miniconda3/bin/activate
 
-            # # sanitize the input commit message and PR body here:
-            # #
-            # # trim all new lines from commit messages + PR_BODY to avoid issues with batch environment
-            # # variable copying. see https://github.com/pytorch/pytorch/pull/80043#issuecomment-1167796028
-            # COMMIT_MESSAGES="${COMMIT_MESSAGES//[$'\n\r']}"
-            # PR_BODY="${PR_BODY//[$'\n\r']}"
+      #       # # sanitize the input commit message and PR body here:
+      #       # #
+      #       # # trim all new lines from commit messages + PR_BODY to avoid issues with batch environment
+      #       # # variable copying. see https://github.com/pytorch/pytorch/pull/80043#issuecomment-1167796028
+      #       # COMMIT_MESSAGES="${COMMIT_MESSAGES//[$'\n\r']}"
+      #       # PR_BODY="${PR_BODY//[$'\n\r']}"
 
-            # # then trim all special characters like single and double quotes to avoid unescaped inputs to
-            # # wreak havoc internally
-            # export COMMIT_MESSAGES="${COMMIT_MESSAGES//[\'\"]}"
-            # export PR_BODY="${PR_BODY//[\'\"]}"
+      #       # # then trim all special characters like single and double quotes to avoid unescaped inputs to
+      #       # # wreak havoc internally
+      #       # export COMMIT_MESSAGES="${COMMIT_MESSAGES//[\'\"]}"
+      #       # export PR_BODY="${PR_BODY//[\'\"]}"
 
-            python3 -mpip install dist/*.whl
-            .jenkins/pytorch/macos-test.sh
-      - run:
-          name: Report results
-          no_output_timeout: "5m"
-          command: |
-            set -ex
-            source /Users/distiller/workspace/miniconda3/bin/activate
-            python3 -m pip install boto3==1.19.12
+      #       python3 -mpip install dist/*.whl
+      #       .jenkins/pytorch/macos-test.sh
+      # - run:
+      #     name: Report results
+      #     no_output_timeout: "5m"
+      #     command: |
+      #       set -ex
+      #       source /Users/distiller/workspace/miniconda3/bin/activate
+      #       python3 -m pip install boto3==1.19.12
 
-            export JOB_BASE_NAME=$CIRCLE_JOB
+      #       export JOB_BASE_NAME=$CIRCLE_JOB
 
-            # Using the same IAM user to write stats to our OSS bucket
-            export AWS_ACCESS_KEY_ID=${CIRCLECI_AWS_ACCESS_KEY_FOR_SCCACHE_S3_BUCKET_V4}
-            export AWS_SECRET_ACCESS_KEY=${CIRCLECI_AWS_SECRET_KEY_FOR_SCCACHE_S3_BUCKET_V4}
-            python -m tools.stats.print_test_stats --upload-to-s3 --compare-with-s3 test
-      - store_test_results:
-          path: test/test-reports
+      #       # Using the same IAM user to write stats to our OSS bucket
+      #       export AWS_ACCESS_KEY_ID=${CIRCLECI_AWS_ACCESS_KEY_FOR_SCCACHE_S3_BUCKET_V4}
+      #       export AWS_SECRET_ACCESS_KEY=${CIRCLECI_AWS_SECRET_KEY_FOR_SCCACHE_S3_BUCKET_V4}
+      #       python -m tools.stats.print_test_stats --upload-to-s3 --compare-with-s3 test
+      # - store_test_results:
+      #     path: test/test-reports
 
 
   pytorch_macos_10_13_py3_test:
@@ -1420,8 +1437,37 @@ workflows:
               only:
                 - postnightly
       - mac_build:
+          name: macos-12-py3-x86-64-build
+          build-environment: macos-12-py3-x86-64
+          xcode-version: "13.3.1"
+      - mac_test:
+          name: macos-12-py3-x86-64-test
+          build-environment: macos-12-py3-x86-64
+          xcode-version: "13.3.1"
+          shard-number: "1"
+          num-test-shards: "2"
+          requires:
+            - macos-12-py3-x86-64-build
+      - mac_test:
+          name: macos-12-py3-x86-64-test-a
+          build-environment: macos-12-py3-x86-64
+          xcode-version: "13.3.1"
+          shard-number: "1"
+          num-test-shards: "2"
+          requires:
+            - macos-12-py3-x86-64-build
+            - macos-12-py3-x86-64-lite-interpreter-build-test
+      - mac_build:
           name: macos-12-py3-x86-64-lite-interpreter-build-test
           build-environment: macos-12-py3-lite-interpreter-x86-64
           xcode-version: "13.3.1"
           build-generates-artifacts: false
+      - mac_test:
+          name: macos-12-py3-x86-64-test-b
+          build-environment: macos-12-py3-x86-64
+          xcode-version: "13.3.1"
+          shard-number: "1"
+          num-test-shards: "2"
+          requires:
+            - macos-12-py3-x86-64-lite-interpreter-build-test
     when: << pipeline.parameters.run_build >>
